adminapp/urls.py
from adminapp import views as admin_views
from django.urls import path

app_name = 'admin_views'

urlpatterns = [
    path('users/create/', admin_views.UserCreateView.as_view(), name='user_create'),
    path('users/', admin_views.UserListView.as_view(), name='user_list'),
    path('users/update/<int:pk>/', admin_views.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', admin_views.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', admin_views.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/', admin_views.ProductCategoriesListView.as_view(), name='category_list'),
    path('categories/update/<int:pk>/', admin_views.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', admin_views.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/<int:pk>/', admin_views.ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/', admin_views.ProductsListView.as_view(), name='product_list'),
    path('products/detail/<int:pk>/', admin_views.ProductDetailView.as_view(), name='product_detail'),
    path('products/update/<int:pk>/', admin_views.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', admin_views.ProductDeleteView.as_view(), name='product_delete'),

    path('orders/<int:pk>/', admin_views.OrdersListView.as_view(), name='orders_list'),
    path('orders/complete/forming/<int:pk>/', admin_views.order_forming_complete, name='orders_forming_complete'),
    path('orders/detail/<int:pk>/', admin_views.OrderDetailView.as_view(), name='orders_detail'),
    path('orders/update/<int:pk>/', admin_views.OrderUpdateView.as_view(), name='orders_update'),
    path('orders/delete/<int:pk>/', admin_views.OrderDeleteView.as_view(), name='orders_delete'),

    path('statistics/', admin_views.sales_statistics, name='statistics'),
]

authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'


urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<key>/', authapp.verify, name='verify'),
    path('api/reg/', authapp.RegistrationAPIView.as_view(), name='APIreg'),
    path('api/log/', authapp.LoginAPIView.as_view(), name='APIlog'),
    path('api/load/', authapp.LoadAPIView.as_view(), name='APIload'),
]

basketapp/urls.py
from django.urls import path
from basketapp import views as basket

app_name = 'basketapp'

urlpatterns = [
    path('', basket.basket, name='basket'),
    path('add/<int:pk>/', basket.add, name='add'),
    path('remove/<int:pk>/', basket.remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket.edit, name='edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as mainapp

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('', include('social_django.urls', namespace='social')),
    path('contact/', mainapp.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('old_admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('favourite/', include('favouritesapp.urls', namespace='favourite')),
    path('favorite/', mainapp.favorite_products, name='fav'),
    path('merchant/', include('interkassaapp.urls', namespace='merchant')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path
from mainapp import views as mainapp
# from django.views.decorators.cache import cache_page

app_name = 'mainapp'

urlpatterns = [
    # path('', cache_page(3600)(mainapp.products), name='products'),
    path('', mainapp.products, name='products'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('category/<int:pk>/<int:page>/', mainapp.products, name='category_page'),
    path('product/<int:pk>/', mainapp.product, name='product'),
    path('search/', mainapp.SearchResultsView.as_view(), name='search_results'),
    # path('load/', mainapp.postman, name='load'),
]

ordersapp/urls.py
from django.urls import path
from ordersapp import views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderListView.as_view(), name='list'),
    path('read/<pk>/', ordersapp.OrderDetailView.as_view(), name='read'),
    path('create/', ordersapp.OrderCreateView.as_view(), name='create'),
    path('update/<pk>/', ordersapp.OrderUpdateView.as_view(), name='update'),
    path('delete/<pk>/', ordersapp.OrderDeleteView.as_view(), name='delete'),
    path('complete/forming/<pk>/', ordersapp.order_forming_complete, name='forming_complete'),
    path('product/price/<int:pk>/', ordersapp.get_product_price, name='get_product_price'),
]

mainapp/models.py
from django.db import models

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='название')
    description = models.TextField(verbose_name='описание')
    is_active = models.BooleanField(default=True)


    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('-id',)

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name='категория')
    name = models.CharField(max_length=128, verbose_name='название')
    image = models.ImageField(upload_to='products', blank=True, verbose_name='картинка')
    short_desc = models.CharField(max_length=255, blank=True, verbose_name='краткое описание')
    description = models.TextField(blank=True, verbose_name='описание')
    price = models.DecimalField(decimal_places=2, max_digits=10, default=0, verbose_name='цена')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='количество')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name}({self.category.name})'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ['-id']

mainapp/views.py
import random
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from mainapp.models import Product, ProductCategory
from django.views.generic import ListView
from django.conf import settings
from django.core.cache import cache
from django.views.decorators.cache import cache_page
from mainapp.context_processors import dollars
from favouritesapp.models import FavoriteProducts


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'categories'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category_item = cache.get(key)
        if category_item is None:
            category_item = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category_item)
        return category_item
    return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_orederd_by_price():
    if settings.LOW_CACHE:
        key = 'products_orederd_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_orederd_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_orederd_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by(
                'price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')


def get_hot_product():
    products = get_products()
    # return random.sample(list(Product.objects.all()), 1)[0]
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    products_list = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk).select_related(
        'category')[:3]
    return products_list


def index(request):
    context = {
        'title': 'Главная',
        'products': get_products()[:4],
    }
    return render(request, 'mainapp/index.html', context)


def contact(request):
    context = {
        'title': 'Контакты',
    }
    return render(request, 'mainapp/contact.html', context)


@cache_page(3600)
def products(request, pk=None, page=1):
    links_menu = get_links_menu()
    # links_menu = ProductCategory.objects.all()
    if pk is not None:
        if pk == 0:
            products_list = Product.objects.all()
            category_item = {
                'name': 'все',
                'pk': 0,
            }
        else:
            category_item = get_category(pk)
            products_list = get_products_in_category_orederd_by_price(pk)
        paginator = Paginator(products_list, 3)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)
        context = {
            'links_menu': links_menu,
            'title': 'Продукты',
            'category': category_item,
            'products': products_paginator,
        }
        return render(request, 'mainapp/products_list.html', context=context)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    context = {
        'links_menu': links_menu,
        'title': 'Продукты',
        'hot_product': hot_product,
        'same_products': same_products,
    }
    return render(request, 'mainapp/products.html', context=context)


def product(request, pk):
    favorite = FavoriteProducts.objects.filter(product_id=pk, user_id=request.user)
    context = {
        'favorite': favorite,
        'product': get_product(pk),
        'price_in_dollars': float(get_product(pk).price) / dollars(request)['dollars'],
        'links_menu': get_links_menu(),
    }
    return render(request, 'mainapp/product.html', context)


def favorite_products(request):
    favorite = FavoriteProducts.objects.filter(user_id=request.user)
    context = {
        'favorite': favorite,
    }
    return render(request, 'mainapp/favorite_products.html', context)


class SearchResultsView(ListView):
    model = Product
    template_name = 'mainapp/search_results.html'

mainapp/templates/mainapp/includes/inc_main_menu.html
<a href="{% url 'index' %}" class="logo"></a>
<ul class="menu">
    <li>
        <a href="{% url 'index' %}"
           {% if request.resolver_match.url_name == 'index' %}class="active"{% endif %}>домой</a>
    </li>

    <li>
        <a href="{% url 'products:products' %}"
           {% if request.resolver_match.namespace == 'products' %}class="active"{% endif %}>продукты</a>
    </li>
    <li>
        <a href="{% url 'contact' %}" {% if request.resolver_match.url_name == 'contact' %}class="active"{% endif %}>контакты</a>
    </li>
    {% if user.is_authenticated %}
        <li>
            <a href="{% url 'fav' %}"
               {% if request.resolver_match.url_name == 'fav' %}class="active"{% endif %}>любимое</a>
        </li>
    {% endif %}
    {% if user.is_authenticated %}
        <li><a class="log_regedit" href="{% url 'order:list' %}">заказы</a></li>
        <li><a class="log_regedit" href="{% url 'auth:edit' %}">{{ user.first_name|default:'пользователь' }}</a></li>
        <li><a class="log_entexit" href="{% url 'auth:logout' %}">выйти</a></li>
    {% else %}
        <li><a class="log_regedit" href="{% url 'auth:register' %}">регистрация</a></li>
        <li><a class="log_entexit" href="{% url 'auth:login' %}">войти</a></li>
    {% endif %}
    {#    {% if user.is_authenticated %}#}
    {#        <li>#}
    {#            <div class="dropdown">#}
    {#                <a class="dropdown-toggle" href="" data-toggle="dropdown">#}
    {#                    {{ user.first_name|default:'Пользователь' }}#}
    {#                    <span class="caret"></span>#}
    {#                </a>#}
    {#                <ul class="dropdown-menu">#}
    {#                    <li><a href="{% url 'auth:edit' %}">профиль</a></li>#}
    {#                                        <li><a href="{% url 'ordersapp:orders_list' %}">заказы</a></li>#}
    {#                    <li><a href="#">заказы</a></li>#}
    {#                    <li><a class="log_entexit" href="{% url 'auth:logout' %}">выйти</a></li>#}
    {#                </ul>#}
    {#            </div>#}
    {#        </li>#}
    {#    {% else %}#}
    {#        <li><a class="log_regedit" href="{% url 'auth:register' %}">регистрация</a></li>#}
    {#        <li><a class="log_entexit" href="{% url 'auth:login' %}">войти</a></li>#}
    {#    {% endif %}#}
    {% if user.is_superuser %}
        <li><a class="log_admin" href="{% url 'adminapp:user_list' %}">админка</a></li>
    {% endif %}
    <li>Курс: {{ dollars }}</li>

</ul>
<a href="#" class="search"></a>
{#<form action="{% url 'search_results' %}" method="get">#}
{#  <input name="q" type="text" placeholder="Search...">#}
{#</form>#}
<a href="{% url 'basket:basket' %}" class="basket">
    {#    {% if basket.lenght > 0 %}#}
    {% if basket %}
        {{ basket.0.total_cost|floatformat:0 }} руб. <br>
        {{ basket.0.total_quantity }} шт.
    {% endif %}
    {#    <p class="basket_count">{% if basket %}{{ basket.count }}{% endif %}</p>#}
</a>

{#<a href="{% url 'basket:basket' %}" class="basket"><p class="basket_count">{% if basket %}{{ basket }}{% endif %}</p></a>#}