adminapp/urls.py
from adminapp import views as admin_views
from django.urls import path

app_name = 'admin_views'

urlpatterns = [
    path('users/create/', admin_views.UserCreateView.as_view(), name='user_create'),
    path('users/', admin_views.UserListView.as_view(), name='user_list'),
    path('users/update/<int:pk>/', admin_views.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', admin_views.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', admin_views.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/', admin_views.ProductCategoriesListView.as_view(), name='category_list'),
    path('categories/update/<int:pk>/', admin_views.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', admin_views.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/<int:pk>/', admin_views.ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/', admin_views.ProductsListView.as_view(), name='product_list'),
    path('products/detail/<int:pk>/', admin_views.ProductDetailView.as_view(), name='product_detail'),
    path('products/update/<int:pk>/', admin_views.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', admin_views.ProductDeleteView.as_view(), name='product_delete'),

    path('orders/<int:pk>/', admin_views.OrdersListView.as_view(), name='orders_list'),
    path('orders/complete/forming/<int:pk>/', admin_views.order_forming_complete, name='orders_forming_complete'),
    path('orders/detail/<int:pk>/', admin_views.OrderDetailView.as_view(), name='orders_detail'),
    path('orders/update/<int:pk>/', admin_views.OrderUpdateView.as_view(), name='orders_update'),
    path('orders/delete/<int:pk>/', admin_views.OrderDeleteView.as_view(), name='orders_delete'),

    path('statistics/', admin_views.sales_statistics, name='statistics'),
]

authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'


urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<key>/', authapp.verify, name='verify'),
    path('api/reg/', authapp.RegistrationAPIView.as_view(), name='APIreg'),
    path('api/log/', authapp.LoginAPIView.as_view(), name='APIlog'),
    path('api/load/', authapp.LoadAPIView.as_view(), name='APIload'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as mainapp

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('', include('social_django.urls', namespace='social')),
    path('contact/', mainapp.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('old_admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('favourite/', include('favouritesapp.urls', namespace='favourite')),
    path('favorite/', mainapp.favorite_products, name='fav'),
    path('merchant/', include('interkassaapp.urls', namespace='merchant')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

adminapp/models.py
from django.db import models

# Create your models here.

ordersapp/models.py
from django.conf import settings
from django.db import models

from mainapp.models import Product


class Order(models.Model):
    STATUS_FORMING = 'FM'
    STATUS_SEND_TO_PROCEED = 'STP'
    STATUS_PROCEEDED = 'PRD'
    STATUS_PAID = 'PD'
    STATUS_DONE = 'DN'
    STATUS_CANCELED = 'CN'

    STATUSES = (
        (STATUS_FORMING, 'Формируется'),
        (STATUS_SEND_TO_PROCEED, 'Отправлен в обработку'),
        (STATUS_PROCEEDED, 'Обработан'),
        (STATUS_PAID, 'Оплачен'),
        (STATUS_DONE, 'Готов'),
        (STATUS_CANCELED, 'Отменён'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    status = models.CharField(choices=STATUSES, default=STATUS_FORMING, max_length=3, verbose_name='статус')
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_at',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return 'Текущий заказ: {}'.format(self.id)

    def get_total_quantity(self):
        _items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, _items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        _items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.product_cost, _items)))

    # def delete(self, *args, **kwargs):
    #     for item in self.orderitems.select_related():
    #         item.product.quantity += item.quantity
    #         item.product.save()
    #     self.is_active = False
    #     self.save()

    def get_summary(self):
        items = self.orderitems.select_related()
        return {
            'total_cost': sum(list(map(lambda x: x.product_cost, items))),
            'total_quantity': sum(list(map(lambda x: x.quantity, items))),
        }


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='orderitems')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество')

    @property
    def product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk)

adminapp/forms.py
from authapp.forms import ShopUserEditForm, ShopUserProfileEditForm
from authapp.models import ShopUser, ShopUserProfile
from mainapp.models import ProductCategory, Product
from django import forms


class ShopUserAdminEdit(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'
        exclude = ('is_active',)


class ShopUserProfileEdit(ShopUserProfileEditForm):
    class Meta:
        model = ShopUserProfile
        fields = '__all__'
        exclude = ('is_active',)


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'
        exclude = ('is_active',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        exclude = ('is_active',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductCategoryCreateForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'
        exclude = ('is_active',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.db import transaction
from django.db.models import F, Q
from django.db.models.aggregates import Sum, Count, Avg
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, ListView, CreateView, DeleteView, UpdateView
from adminapp.forms import ShopUserAdminEdit, ProductCategoryEditForm, ProductEditForm, ProductCategoryCreateForm, \
    ProductCreateForm, ShopUserProfileEdit
from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser
from basketapp.models import Basket
from mainapp.models import Product, ProductCategory
from ordersapp.forms import OrderItemForm
from ordersapp.models import Order, OrderItem
import collections


class AccessMixin:
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class DeleteClass:
    def delete(self, request, *args, **kwargs):
        success_url = self.get_success_url()
        if request.method == 'POST':
            checkbox = request.POST.get('del_box', None)
        if checkbox:
            self.object = self.get_object()
            self.object.delete()
            return HttpResponseRedirect(success_url)
        else:
            self.object = self.get_object()
            if self.object.is_active:
                self.object.is_active = False
            else:
                self.object.is_active = True
            self.object.save()
            return HttpResponseRedirect(success_url)


class UserCreateView(AccessMixin, CreateView):
    model = ShopUser
    template_name = 'adminapp/user_form.html'
    success_url = reverse_lazy('adminapp:user_list')
    form_class = ShopUserRegisterForm


class UserListView(AccessMixin, ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['object_list'] = ShopUser.objects.all().order_by('-is_active')
        return context_data


class UserUpdateView(AccessMixin, UpdateView):
    model = ShopUser
    template_name = 'adminapp/user_form.html'
    form_class = ShopUserAdminEdit
    success_url = reverse_lazy('adminapp:user_list')


class UserDeleteView(AccessMixin, DeleteClass, DeleteView, ):
    model = ShopUser
    template_name = 'adminapp/user_delete.html'

    def get_success_url(self):
        return reverse('adminapp:user_list')


class ProductCategoryCreateView(AccessMixin, CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_form.html'
    success_url = reverse_lazy('adminapp:category_list')
    form_class = ProductCategoryCreateForm


class ProductCategoriesListView(AccessMixin, ListView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['object_list'] = ProductCategory.objects.all().order_by('-is_active')
        return context_data


class ProductCategoryUpdateView(AccessMixin, UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_form.html'
    success_url = reverse_lazy('adminapp:category_list')
    form_class = ProductCategoryEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории/редактирование'
        return context


class ProductCategoryDeleteView(AccessMixin, DeleteClass, DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'

    def get_success_url(self):
        return reverse('adminapp:category_list')


class ProductsListView(AccessMixin, ListView):
    model = Product
    template_name = 'adminapp/products.html'
    paginate_by = 4

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['category'] = get_object_or_404(ProductCategory, pk=self.kwargs.get('pk'))
        return context_data

    def get_queryset(self):
        return Product.objects.filter(category__pk=self.kwargs.get('pk'))

    def get_success_url(self):
        product_item = Product.objects.get(pk=self.kwargs['pk'])
        return reverse('adminapp:product_list', args=[product_item.category_id])


class ProductCreateView(AccessMixin, CreateView):
    model = Product
    template_name = 'adminapp/product_form.html'
    form_class = ProductCreateForm

    def get_success_url(self):
        product_item = Product.objects.get(pk=self.kwargs['pk'])
        return reverse('adminapp:product_list', args=[product_item.category_id])

    def get(self, request, **kwargs):
        form = ProductCreateForm(initial={'category': get_object_or_404(ProductCategory, pk=self.kwargs['pk'])})
        return render(request, 'adminapp/product_form.html', {'form': form})


class ProductUpdateView(AccessMixin, UpdateView):
    model = Product
    template_name = 'adminapp/product_form.html'
    form_class = ProductEditForm

    def get_success_url(self):
        product_item = Product.objects.get(pk=self.kwargs['pk'])
        return reverse('adminapp:product_list', args=[product_item.category_id])


class ProductDeleteView(AccessMixin, DeleteClass, DeleteView):
    model = Product
    template_name = 'adminapp/product_delete.html'

    def get_success_url(self):
        product_item = Product.objects.get(pk=self.kwargs['pk'])
        return reverse('adminapp:product_list', args=[product_item.category_id])


class ProductDetailView(AccessMixin, DetailView):
    model = Product
    template_name = 'adminapp/product_detail.html'


class OrdersListView(AccessMixin, ListView):
    model = Order
    template_name = 'adminapp/orders.html'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['object_list'] = Order.objects.filter(user_id=self.kwargs.get('pk')).order_by('-is_active')
        return context_data

    def get_queryset(self):
        return Order.objects.filter(user_id=self.kwargs.get('pk'))



class OrderUpdateView(AccessMixin, UpdateView):
    model = Order
    fields = []
    template_name = 'adminapp/order_edit.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, OrderItemForm, extra=1)
        if self.request.POST:
            formset = OrderFormSet(self.request.POST, instance=self.object)
        else:
            formset = OrderFormSet(instance=self.object)
        context_data['orderitems'] = formset
        return context_data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']
        with transaction.atomic():
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()
        if self.object.get_total_cost() == 0:
            self.object.delete()
        return super().form_valid(form)

    def get_success_url(self):
        order_item = Order.objects.get(pk=self.kwargs['pk'])
        return reverse('adminapp:orders_list', args=[order_item.user_id])


class OrderDeleteView(AccessMixin, DeleteClass, DeleteView):
    model = Order
    template_name = 'adminapp/order_delete.html'

    def get_success_url(self):
        order_item = Order.objects.get(pk=self.kwargs['pk'])
        return reverse('adminapp:orders_list', args=[order_item.user_id])


class OrderDetailView(AccessMixin, DetailView):
    model = Order
    template_name = 'adminapp/order_detail.html'


def order_forming_complete(request, pk):
    order_item = Order.objects.filter(pk=pk).get()
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.STATUS_SEND_TO_PROCEED
    order.save()
    return HttpResponseRedirect(reverse('adminapp:orders_list', args=[order_item.user_id]))


def sales_statistics(request):
    sales_query = OrderItem.objects.filter(Q(order__status='STP'))\
        .values('product_id', 'product__name', 'product__image', 'product__price').annotate(quantity=Sum('quantity'))
    context = {
        'sales_query': sales_query,
    }
    return render(request, 'adminapp/statistics.html', context)

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="categories_list">
        <a class="adminadd_button" href={% url 'adminapp:category_create' %}>
            <span>новая категория</span>
        </a>
        {% for object in object_list %}
            <div class="category_record {% if not object.is_active %}not_active{% endif %}">
                <div class="category_name">
                    {{ object.name|title }}
                </div>
                <div class="category_actions">
                    <button>
                        <a href={% url 'adminapp:product_list' object.pk %}>
                            товары категории
                        </a>
                    </button>
                    <button>
                        <a href={% url 'adminapp:category_update' object.pk %}>
                            редактировать
                        </a>
                    </button>
                    <button>
                        <a href={% url 'adminapp:category_delete' object.pk %}>
                            {% if object.is_active %}
                                удалить
                            {% else %}
                                восстановить
                            {% endif %}
                        </a>
                    </button>
                </div>
                <div class="category_desc">
                    {{ object.description|title }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <div class="del_block">
        {% if object.is_active %}
            Уверены, что хотите удалить категорию {{ category.name }}?
        {% else %}
            Уверены, что хотите востановить категорию?
        {% endif %}
        <form method="post">
            {% if object.is_active %}
                <label><input type="checkbox" name="del_box" value="True">Удалить полностью</label>
                <br>
            {% endif %}
            {% csrf_token %}
            <input type="submit" class="btn-block btn-danger col-lg-12" value="Да">
        </form>
        <button onclick="document.location='{% url 'adminapp:category_list' %}'"
                class="btn-block btn-success col-lg-12">
            Отмена
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/category_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <div class="admin_block">
        <a href="{% url 'adminapp:category_list' %}" class="admin_cross"></a>
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Сохранить" class="btn-block btn-primary col-lg-12">

        </form>
    </div>
{% endblock %}

adminapp/templates/adminapp/order_detail.html
{% extends "adminapp/base.html" %}
{% load static %}
{#{% load my_tags %}#}

{% block content %}
    <div class="admin_block">
        <div class="products_list_admin">
            <a class="admin_cross" href={% url 'adminapp:orders_list' user.id %}></a>
            <div>
                {% include 'adminapp/includes/inc_order_summary.html' %}
            </div>
            {% for item in object.orderitems.select_related %}
                <div class="order_record">
                    <img src="/media/{{ item.product.image }}"
                            {#                <img src="{{ item.product.image|media_folder_products }}"#}
                         alt="{{ item.product.short_desc }}">
                    <span class="category_name">
                   {{ item.product.category.name }}
               </span>
                    <span class="product_name">{{ item.product.name }}</span>
                    <span class="product_price">
                   {{ item.product.price }}&nbspруб
               </span>
                    <span class="product_quantitiy">
                   x {{ item.quantity }} шт.
               </span>
                    <span class="product_cost">
                    = {{ item.get_product_cost }}&nbspруб
               </span>
                </div>
            {% endfor %}
            <button class="btn btn-warning btn-round form-control last">
                <a href="{% url 'adminapp:orders_forming_complete' object.pk %}">
                    совершить покупку
                </a>
            </button>
            <button class="btn btn-default btn-round form-control last">
                <a href="{% url 'adminapp:orders_delete' object.pk %}">
                    {% if object.is_active %}
                        удалить
                    {% else %}
                        восстановить
                    {% endif %}
                </a>
            </button>
{#            <button class="btn btn-info btn-round form-control last">#}
{#                <a href="{% url 'adminapp:orders_list' object.user_id %}">#}
{#                    к списку заказов#}
{#                </a>#}
{#            </button>#}
        </div>
    </div>
    {#    <button class="btn btn-default btn-round form-control last">#}
    {#        <a href="{% url 'index' %}">на главную</a>#}
    {#    </button>#}
{% endblock %}

adminapp/templates/adminapp/orders.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load media_tags %}

{% block content %}

    {#    {% include 'adminapp/includes/inc_paginator.html' %}#}

    {#    <a class="adminadd_button" href={% url 'adminapp:orders_list' category.pk %}>#}
    {#        <span>новый продукт</span>#}
    {#    </a>#}
    {#        <a href="{% url 'adminapp:orders_list' object.pk %}">#}
    {#            к списку заказов#}
    {#        </a>#}

    <div class="admin_block">
        <div class="products_list_admin">
            <a class="admin_cross" href={% url 'adminapp:user_list' %}></a>
            <table class="table orders_list">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Активен</th>
                    <th>Создан</th>
                    <th>Обновлен</th>
                    <th>Статус</th>
                </tr>
                </thead>
                <tbody>
                {% for object in object_list %}
                    <tr>
                        <td class="td1 orders_list">{{ object.pk }}</td>
                        <td>{{ object.is_active }}</td>
                        <td>{{ object.created_at|date:"Y-m-d H:i:s" }}</td>
                        <td>{{ object.updated_at|date:"Y-m-d H:i:s" }}</td>
                        <td>{{ object.get_status_display }}</td>
                        <td>
                            <a href="{% url 'admin_views:orders_detail' object.pk %}">
                                посмотреть
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'adminapp:orders_update' object.pk %}">
                                редактировать
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'adminapp:orders_delete' object.pk %}">
                                {% if object.is_active %}
                                    удалить
                                {% else %}
                                    восстановить
                                {% endif %}
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_detail.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="product_read">

            <img src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">
            <div class="summary">
                <b><strong>{{ object.category.name|title }} / {{ object.name|title }}</strong></b>
                <br>
                <br>
                <b>цена</b>

                <p>{{ object.price }}</p>
                <b>количество</b>
                <p>{{ object.quantity }}</p>
                <b>в каталоге</b>
                <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
                <p>
                    <button>
                        <a href={% url 'adminapp:product_update' object.pk %}>Редактировать</a>
                    </button>
                </p>
                <p>
                    <button>
                        <a href={% url 'adminapp:product_delete' object.pk %}>Удалить</a>
                    </button>
                </p>
                <p>
                    <button>
                        <a href={% url 'adminapp:product_list' object.category.pk %}>назад</a>
                    </button>
                </p>
                <div class="product_desc">
                    <b>краткая информация</b>
                    <p>
                        {{ object.short_desc }}
                    </p>
                    <br>
                    <b>подробная информация</b>
                    <p>
                        {{ object.description }}
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <div class="admin_block">
        <a class="admin_cross" href={% url 'adminapp:product_list' form.category.value %} ></a>
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Сохранить" class="btn-block btn-primary col-lg-12">
        </form>
    </div>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load media_tags %}

{% block content %}

    {% include 'adminapp/includes/inc_paginator.html' %}

    <a class="adminadd_button" href={% url 'adminapp:product_create' category.pk %}>
        <span>новый продукт</span>
    </a>



    <div class="products_list">
        {% for object in object_list %}
            <div class="product_record {% if not object.is_active %}not_active{% endif %}">
                <img src="{{ object.image|media_for_products }}"
                     alt="{{ object.name }}">
                <div class="product_name">
                    {{ object.name|title }}
                </div>
                <div class="product_actions">
                    <button>
                        <a href={% url 'adminapp:product_detail' object.pk %}>
                            подробнее
                        </a>
                    </button>
                    <button>
                        <a href={% url 'adminapp:product_update' object.pk %}>
                            редактировать
                        </a>
                    </button>
                    <button>
                        <a href={% url 'adminapp:product_delete' object.pk %}>
                            {% if object.is_active %}
                                удалить
                            {% else %}
                                восстановить
                            {% endif %}
                        </a>
                    </button>
                </div>
                <div class="summary">
                    <b>цена</b>
                    <p>{{ object.price }} руб</p>
                    <b>количество</b>
                    <p>{{ object.quantity }}</p>
                </div>
                <div class="product_desc">
                    {{ object.short_desc|title }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load media_tags %}

{% block content %}
    <div class="users_list">
        <a class="adminadd_button" href={% url 'adminapp:user_create' %}>
            <span>новый пользователь</span>
        </a>
        {% for object in object_list %}
            <div class="user_record {% if not object.is_active %}not_active{% endif %} user_box {% if object.is_superuser %}admin_highlight{% endif %}">
                <img src="{{ object.avatar|media_for_users }}" alt="{{ object.username }}">
                <div class="user_role">
                    {% if object.is_superuser %}
                        <h4>
                            <span class="text-danger">администратор</span>
                        </h4>
                    {% else %}
                        пользователь
                    {% endif %}
                    <br>
                    <a class="admin_button" href={% url 'adminapp:orders_list' object.pk %}>
                        заказы
                    </a>
                    <a class="admin_button" href={% url 'adminapp:user_update' object.pk %}>
                        редактировать
                    </a>
                    <br>
                    <a class="admin_button" href={% url 'adminapp:user_delete' object.pk %}>
                        {% if object.is_active %}
                            удалить
                        {% else %}
                            восстановить
                        {% endif %}
                    </a>
                </div>
                <div class="user_name">
                    <p><strong>{{ object.username }}</strong></p>
                    <p>
                        {% if object.first_name %}
                            <b>{{ object.first_name|title }}</b>
                            {% if object.last_name %}
                                <p>{{ object.last_name|title }}</p>
                            {% endif %}
                        {% endif %}
                    </p>
                </div>
                <div class="user_age">
                    age:<br>
                    {{ object.age }} лет
                </div>
                <div class="user_email">
                    email:<br>
                    {{ object.email }}
                </div>
                <div class="user_lastlogin">
                    logged:<br>
                    {{ object.last_login }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}