authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'


urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<key>/', authapp.verify, name='verify'),
    path('api/reg/', authapp.RegistrationAPIView.as_view(), name='APIreg'),
    path('api/log/', authapp.LoginAPIView.as_view(), name='APIlog'),
    path('api/load/', authapp.LoadAPIView.as_view(), name='APIload'),
]

basketapp/urls.py
from django.urls import path
from basketapp import views as basket

app_name = 'basketapp'

urlpatterns = [
    path('', basket.basket, name='basket'),
    path('add/<int:pk>/', basket.add, name='add'),
    path('remove/<int:pk>/', basket.remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket.edit, name='edit'),
]

favouritesapp/urls.py
from django.urls import path
from favouritesapp import views as favourite

app_name = 'favouritesapp'

urlpatterns = [
    path('add/<int:pk>/', favourite.add, name='add'),
    path('remove/<int:pk>/', favourite.remove, name='remove'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as mainapp

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('', include('social_django.urls', namespace='social')),
    path('contact/', mainapp.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('old_admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('favourite/', include('favouritesapp.urls', namespace='favourite')),
    path('favorite/', mainapp.favorite_products, name='fav'),
    path('merchant/', include('interkassaapp.urls', namespace='merchant')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path
from mainapp import views as mainapp
# from django.views.decorators.cache import cache_page

app_name = 'mainapp'

urlpatterns = [
    # path('', cache_page(3600)(mainapp.products), name='products'),
    path('', mainapp.products, name='products'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('category/<int:pk>/<int:page>/', mainapp.products, name='category_page'),
    path('product/<int:pk>/', mainapp.product, name='product'),
    path('search/', mainapp.SearchResultsView.as_view(), name='search_results'),
    # path('load/', mainapp.postman, name='load'),
]

mainapp/models.py
from django.db import models

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='название')
    description = models.TextField(verbose_name='описание')
    is_active = models.BooleanField(default=True)


    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('-id',)

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, verbose_name='категория')
    name = models.CharField(max_length=128, verbose_name='название')
    image = models.ImageField(upload_to='products', blank=True, verbose_name='картинка')
    short_desc = models.CharField(max_length=255, blank=True, verbose_name='краткое описание')
    description = models.TextField(blank=True, verbose_name='описание')
    price = models.DecimalField(decimal_places=2, max_digits=10, default=0, verbose_name='цена')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='количество')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name}({self.category.name})'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ['-id']

mainapp/views.py
import random
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from mainapp.models import Product, ProductCategory
from django.views.generic import ListView
from django.conf import settings
from django.core.cache import cache
from django.views.decorators.cache import cache_page
from mainapp.context_processors import dollars
from favouritesapp.models import FavoriteProducts


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'categories'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category_item = cache.get(key)
        if category_item is None:
            category_item = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category_item)
        return category_item
    return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_orederd_by_price():
    if settings.LOW_CACHE:
        key = 'products_orederd_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_orederd_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_orederd_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by(
                'price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')


def get_hot_product():
    products = get_products()
    # return random.sample(list(Product.objects.all()), 1)[0]
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    products_list = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk).select_related(
        'category')[:3]
    return products_list


def index(request):
    context = {
        'title': 'Главная',
        'products': get_products()[:4],
    }
    return render(request, 'mainapp/index.html', context)


def contact(request):
    context = {
        'title': 'Контакты',
    }
    return render(request, 'mainapp/contact.html', context)


@cache_page(3600)
def products(request, pk=None, page=1):
    links_menu = get_links_menu()
    # links_menu = ProductCategory.objects.all()
    if pk is not None:
        if pk == 0:
            products_list = Product.objects.all()
            category_item = {
                'name': 'все',
                'pk': 0,
            }
        else:
            category_item = get_category(pk)
            products_list = get_products_in_category_orederd_by_price(pk)
        paginator = Paginator(products_list, 3)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)
        context = {
            'links_menu': links_menu,
            'title': 'Продукты',
            'category': category_item,
            'products': products_paginator,
        }
        return render(request, 'mainapp/products_list.html', context=context)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    context = {
        'links_menu': links_menu,
        'title': 'Продукты',
        'hot_product': hot_product,
        'same_products': same_products,
    }
    return render(request, 'mainapp/products.html', context=context)


def product(request, pk):
    favorite = FavoriteProducts.objects.filter(product_id=pk, user_id=request.user)
    context = {
        'favorite': favorite,
        'product': get_product(pk),
        'price_in_dollars': float(get_product(pk).price) / dollars(request)['dollars'],
        'links_menu': get_links_menu(),
    }
    return render(request, 'mainapp/product.html', context)


def favorite_products(request):
    favorite = FavoriteProducts.objects.filter(user_id=request.user)
    context = {
        'favorite': favorite,
    }
    return render(request, 'mainapp/favorite_products.html', context)


class SearchResultsView(ListView):
    model = Product
    template_name = 'mainapp/search_results.html'

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru-ru">
<head>
    <meta charset="utf-8" name="interkassa-verification" content="d62bc634d02290ee7bd12bf87634513a" />
{#    <meta charset="utf-8">#}
    <title>{% block title %}{{ title|title }}{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    {% block css %}
        <link rel="stylesheet" href="{% static 'style.css' %}">
{#        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">#}
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}

    {% block js %}
        <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}

</head>
<body>
<div class="container">

    {% block menu %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    <div class="clr"></div>
</div>

{% block footer %}
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <label>
                        <input type="email" name="email" placeholder="ваш email">
                    </label>
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB {% now "Y" %}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
    </div>
{% endblock %}

</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block menu %}
    <div class="hero">
    <div class="header clearfix">
        {% include 'mainapp/includes/inc_main_menu.html' %}
    </div>

{% endblock %}
{% block content %}
    <h1>наши контакты</h1>
    </div>
    <div class="location">
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>Москва</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>+7-888-888-8888</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>info@geekshop.ru</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>В пределах МКАД</p>
            </div>
        </div>
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>Москва</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>+7-888-888-8888</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>info@geekshop.ru</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>В пределах МКАД</p>
            </div>
        </div>
        <div class="location-1">
            <i class="fa fa-map-marker fa-5x"></i>
            <h4>Москва</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>+7-888-888-8888</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>info@geekshop.ru</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>В пределах МКАД</p>
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/favorite_products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load media_tags %}

{% block menu %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
    </div>
{% endblock %}

{% block content %}
    {% for item in favorite %}
        <div class="basket_record">
            <img src="{{ item.product.image|media_for_products }}"
                 alt="{{ item.product.short_desc }}">
            <span class="category_name">{{ item.product.category.name }}</span>
            <span class="product_name">{{ item.product.name }}</span>
            <span class="product_price">{{ item.product.price }}&nbspруб</span>
            <span class="product_cost">{{ item.cost }}&nbspруб</span>
            <button class="btn btn-round">

                <a href="{% url 'favouritesapp:remove' item.product.id %}" class="">
                    удалить
                </a>
            </button>
        </div>
    {% endfor %}
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
    <div class="slider">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
        <div class="text-slider">
            <h3 class="green">тенденции</h3>
            <h3 class="big"> удобные стулья</h3>
            <p>Новый уровень комфорта. Отличные характеристики.</p>
            <a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
        </div>
        <div class="navi">
            <a href="#"></a><a href="#"></a><a href="#"></a>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="featured">
        <div class="featured-menu">
            <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
        </div>
        <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
        <div class="clearfix">
        </div>
        <div class="tab-content">
            {% for product in products %}
                <div class="block">
                    <a href="{% url 'mainapp:product' product.pk %}"><img src="/media/{{ product.image }}" alt="">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="img">
                            <h4>{{ product.name }}</h4>
                            <p>{{ product.short_desc }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/load.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load media_tags %}

{% block menu %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
    </div>
{% endblock %}

{% block content %}
    {% for item in products %}
        {{ item }}

    {% endfor %}
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html' %}
        </div>
        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/{{ product.image }}" alt="">
                </div>
            </div>
            <div class="description">
                <h3 class="big-bold">{{ product.name }}</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> {{ product.price|floatformat:2  }} <span>руб</span></p>
                <p class="price">{{ price_in_dollars|floatformat:2  }} <span>dol</span></p>
                <a href="{% url 'basket:add' product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                {% if favorite %}
                    <a href="{% url 'favouritesapp:remove' product.pk %}" class="red-button">
                        удалить из избранного <i class="fa fa-chevron-right" aria-hidden="true"></i>
                    </a>
                {% else %}
                    <a href="{% url 'favouritesapp:add' product.pk %}" class="red-button">
                        добавить в избранное <i class="fa fa-chevron-right" aria-hidden="true"></i>
                    </a>
                {% endif %}
{#                <div class="description-text">#}
{#                    <p>{{ product.short_desc }}</p>#}
{#                </div>#}
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load media_tags %}

{% block menu %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html' %}
        </div>
        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="{{ hot_product.image|media_for_products }}" alt="">
                </div>
                    <div class="products_list">
            </div>
            <div class="description">
                <h3 class="big-bold">{{ hot_product.name }}</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> {{ hot_product.price|floatformat:2 }} <span>руб</span></p>
                <a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    <p>{{ hot_product.short_desc }}</p>
                </div>
            </div>
        </div>
        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
            </div>
            <div class="related-products clearfix">
                {% for product in same_products %}
                    <div class="block">
                        <a href="{% url 'mainapp:product' product.pk %}"><img src="{{ product.image|media_for_products }}" alt="">
                            <div class="text">
                                <img src="{% static 'img/icon-hover.png' %}" alt="img">
                                <h4>{{ product.name }}</h4>
                                <p>{{ product.category }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load media_tags %}

{% block menu %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html' %}
        </div>
        <div class="products_list">
            <div class="title clearfix">
                <h2>
                    Категория: "{{ category.name|title }}"
                </h2>
            </div>
            <div class="pagination">
                {% if products.has_previous %}
                    <a href="{% url 'mainapp:category_page' category.pk products.previous_page_number %}"><<</a>
{#                    <a href="{% url 'mainapp:category_page' category.pk %}?p={{ products.previous_page_number }}"></a>#}
                {% endif %}
                {{ products.number }} / {{ products.paginator.num_pages }}
                {% if products.has_next %}
                    <a href="{% url 'mainapp:category_page' category.pk products.next_page_number %}">>></a>
                {% endif %}
            </div>
            <div class="category-products clearfix">
                {% for product in products %}
                    <div class="block">
                        <a href="{% url 'mainapp:product' product.pk %}">
                            <img src="{{ product.image|media_for_products  }}" alt="product">
                            <div class="text">
                                <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                                <h4>{{ product.name }}</h4>
                                <p>{{ product.description }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/search_results.html
<h1>Search Results</h1>

<ul>
    {% for product in object_list %}
        <li>
            {{ product.name }}, {{ product.id }}
        </li>
    {% endfor %}
</ul>