authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'


urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<key>/', authapp.verify, name='verify'),
    path('api/reg/', authapp.RegistrationAPIView.as_view(), name='APIreg'),
    path('api/log/', authapp.LoginAPIView.as_view(), name='APIlog'),
    path('api/load/', authapp.LoadAPIView.as_view(), name='APIload'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as mainapp

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('', include('social_django.urls', namespace='social')),
    path('contact/', mainapp.contact, name='contact'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('order/', include('ordersapp.urls', namespace='order')),
    path('old_admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('favourite/', include('favouritesapp.urls', namespace='favourite')),
    path('favorite/', mainapp.favorite_products, name='fav'),
    path('merchant/', include('interkassaapp.urls', namespace='merchant')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

ordersapp/urls.py
from django.urls import path
from ordersapp import views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderListView.as_view(), name='list'),
    path('read/<pk>/', ordersapp.OrderDetailView.as_view(), name='read'),
    path('create/', ordersapp.OrderCreateView.as_view(), name='create'),
    path('update/<pk>/', ordersapp.OrderUpdateView.as_view(), name='update'),
    path('delete/<pk>/', ordersapp.OrderDeleteView.as_view(), name='delete'),
    path('complete/forming/<pk>/', ordersapp.order_forming_complete, name='forming_complete'),
    path('product/price/<int:pk>/', ordersapp.get_product_price, name='get_product_price'),
]

ordersapp/models.py
from django.conf import settings
from django.db import models

from mainapp.models import Product


class Order(models.Model):
    STATUS_FORMING = 'FM'
    STATUS_SEND_TO_PROCEED = 'STP'
    STATUS_PROCEEDED = 'PRD'
    STATUS_PAID = 'PD'
    STATUS_DONE = 'DN'
    STATUS_CANCELED = 'CN'

    STATUSES = (
        (STATUS_FORMING, 'Формируется'),
        (STATUS_SEND_TO_PROCEED, 'Отправлен в обработку'),
        (STATUS_PROCEEDED, 'Обработан'),
        (STATUS_PAID, 'Оплачен'),
        (STATUS_DONE, 'Готов'),
        (STATUS_CANCELED, 'Отменён'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    status = models.CharField(choices=STATUSES, default=STATUS_FORMING, max_length=3, verbose_name='статус')
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_at',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return 'Текущий заказ: {}'.format(self.id)

    def get_total_quantity(self):
        _items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, _items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        _items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.product_cost, _items)))

    # def delete(self, *args, **kwargs):
    #     for item in self.orderitems.select_related():
    #         item.product.quantity += item.quantity
    #         item.product.save()
    #     self.is_active = False
    #     self.save()

    def get_summary(self):
        items = self.orderitems.select_related()
        return {
            'total_cost': sum(list(map(lambda x: x.product_cost, items))),
            'total_quantity': sum(list(map(lambda x: x.quantity, items))),
        }


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='orderitems')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество')

    @property
    def product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk)

ordersapp/forms.py
from django import forms

from mainapp.models import Product
from ordersapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='Цена руб./шт.', required=False)


    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

        self.fields['product'].queryset = Product.objects.filter(is_active=True).select_related()

ordersapp/views.py
from django.db import transaction
from django.dispatch import receiver
from django.forms.models import inlineformset_factory
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from basketapp.models import Basket
from mainapp.models import Product
from ordersapp.forms import OrderItemForm
from ordersapp.models import Order, OrderItem
from django.db.models.signals import pre_save, pre_delete


class OrderListView(ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderCreateView(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('order:list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, OrderItemForm, extra=1)
        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_items = Basket.objects.filter(user=self.request.user)
            if basket_items.exists():
                OrderFormSet = inlineformset_factory(Order, OrderItem, OrderItemForm, extra=basket_items.count())
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                    form.initial['price'] = basket_items[num].product.price
            else:
                formset = OrderFormSet()
        context_data['orderitems'] = formset
        return context_data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()
                Basket.objects.filter(user=self.request.user).delete()
        if self.object.get_total_cost() == 0:
            self.object.delete()
        return super().form_valid(form)


class OrderUpdateView(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('order:list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, OrderItemForm, extra=1)
        if self.request.POST:
            formset = OrderFormSet(self.request.POST, instance=self.object)
        else:
            queryset = self.object.orderitems.select_related()
            formset = OrderFormSet(instance=self.object, queryset=queryset)
            # formset = OrderFormSet(instance=self.object)
            for form in formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price
        context_data['orderitems'] = formset
        return context_data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']
        with transaction.atomic():
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()
        if self.object.get_total_cost() == 0:
            self.object.delete()
        return super().form_valid(form)


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy('order:list')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class OrderDetailView(DetailView):
    model = Order


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.STATUS_SEND_TO_PROCEED
    order.save()
    return HttpResponseRedirect(reverse('order:list'))


@receiver(pre_save, sender=OrderItem)
@receiver(pre_save, sender=Basket)
def product_quantity_update_save(sender, instance, **kwargs):
    if instance.pk:
        instance.product.quantity -= instance.quantity - sender.get_item(instance.pk).quantity
    else:
        instance.product.quantity -= instance.quantity
    instance.product.save()


@receiver(pre_delete, sender=OrderItem)
@receiver(pre_delete, sender=Basket)
def product_quantity_update_delete(sender, instance, **kwargs):
    instance.product.quantity += instance.quantity
    instance.product.save()


def get_product_price(request, pk):
    if request.is_ajax():
        product_item = Product.objects.filter(pk=pk).first()
        if product_item:
            return JsonResponse({'price': product_item.price})
        return JsonResponse({'price': 0})

ordersapp/templates/ordersapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/jquery.formset.js' %}"></script>
        <script src="{% static 'js/orders.js' %}"></script>
    {% endblock %}
</head>
<body>
<div class="order_container">
    {% block content %}

    {% endblock %}

</div>
</body>
</html>

ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'ordersapp/base.html' %}
{% load static %}

{% block content %}
    <div class="category_delete">
        <div class="h1">Уверены, что хотите удалить?</div>
        {% include 'ordersapp/includes/inc_order_summary.html' %}
        <form action="{% url 'ordersapp:delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'ordersapp:list' %}">отмена</a>
        </button>
    </div>
{% endblock %}

ordersapp/templates/ordersapp/order_detail.html
{% extends "ordersapp/base.html" %}
{% load static %}
{#{% load my_tags %}#}

{% block content %}
    {% include 'ordersapp/includes/inc_order_summary.html' %}


        {% for item in object.orderitems.select_related %}
            <div class="order_record">
                <img  src="/media/{{ item.product.image }}"
{#                <img src="{{ item.product.image|media_folder_products }}"#}
                     alt="{{ item.product.short_desc }}">
                <span class="category_name">
                   {{ item.product.category.name }}
               </span>
                <span class="product_name">{{ item.product.name }}</span>
                <span class="product_price">
                   {{ item.product.price }}&nbspруб
               </span>
                <span class="product_quantitiy">
                   x {{ item.quantity }} шт.
               </span>
                <span class="product_cost">
                    = {{ item.get_product_cost }}&nbspруб
               </span>
            </div>
        {% endfor %}
    {% include 'ordersapp/includes/inc_order_actions.html' %}
{% endblock %}

ordersapp/templates/ordersapp/order_form.html
{% extends "ordersapp/base.html" %}
{% load static %}
{% load cache %}

{% block content %}
    {% include 'ordersapp/includes/inc_order_summary.html' %}
    <div class="order_form">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <table class="table">
                {{ orderitems.management_form }}
                {% for form in orderitems.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">
                                    {{ field.label|capfirst }}
                                </th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="formset_row">
                        {% for field in form.visible_fields %}
                            <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {% if field.name != 'price' %}
                                    {% if field.name == 'product' %}
                                        {% cache 3600 orderitemsform_product field.value %}
                                            {{ field }}
                                        {% endcache %}
                                    {% else %}
                                        {{ field }}
                                    {% endif %}
                                {% else %}
                                    <span class="orderitems-{{ forloop.parentloop.counter0 }}-price">
                                            {% if not field.value %}
                                                {{ 0 }}
                                            {% else %}
                                                {{ field.value }}
                                            {% endif %}
                                    </span> руб.
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <button type="submit" value="сохранить" class="btn btn-default btn-round form-control last">сохранить
            </button>
            {% include 'ordersapp/includes/inc_order_actions.html' %}
        </form>
    </div>

{% endblock %}

ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load static %}


{% block content %}
    <div class="h2 text-center head">
        Ваши заказы,
        {% if user.first_name %}
            {{ user.username }}
            {{ user.first_name|title }}
        {% else %}
            Пользователь
        {% endif %}
    </div>
    <table class="table orders_list">
        <thead>
        <tr>
            <th>ID</th>
            <th>Создан</th>
            <th>Обновлен</th>
            <th>Статус</th>
        </tr>
        </thead>
        <tbody>
        {% for item in object_list %}
            {% if item.is_active %}
                <tr>
                    <td class="td1 orders_list">{{ item.pk }}</td>
                    <td>{{ item.created_at|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ item.updated_at|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ item.get_status_display }}</td>
                    <td>
                        <a href="{% url 'ordersapp:read' item.pk %}">
                            посмотреть
                        </a>
                    </td>
                    <td>
                        {% if item.status == 'FM' %}
                            <a href="{% url 'ordersapp:update' item.pk %}">
                                редактировать
                            </a>
                        {% endif %}
                    </td>
                    <td>
                        {% if item.status == 'FM' %}
                            <a href="{% url 'ordersapp:delete' item.pk %}">
                                удалить
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>
    <button class="btn btn-default btn-round">
        <a href="{% url 'index' %}">
            на главную
        </a>
    </button>
    <button class="btn btn-default btn-round">
        <a href="{% url 'ordersapp:create' %}">
            новый
        </a>
    </button>
{% endblock %}